trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'DevOpsProjectECR'

# no PR triggers
pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
    - job: 'BuildAndPublish'
      steps:
        - task: Bash@3
          displayName: 'Apply config changes from ffdemo'
          inputs:
            targetType: 'inline'
            # script: |
            #   $PWD
            #   cd KeyVaultDemo
            #   #cat Web.config

        - task: Docker@2
          displayName: 'Build Docker image'
          inputs:
            containerRegistry: 'willy container registry'
            repository: 'willycode-demo-web'
            command: 'build'
            Dockerfile: 'Dockerfile'
            buildContext: '.'
            tags: |
              $(Build.BuildId)
              latest
            arguments: '--build-arg     FEED_ACCESSTOKEN=$(VSS_NUGET_ACCESSTOKEN)'
            addPipelineData: false
            addBaseImageData: false

        - task: Docker@2
          displayName: 'Push image to repository'
          inputs:
            containerRegistry: 'willy container registry'
            repository: 'willycode-demo-web'
            command: 'push'
            tags: |
              $(Build.BuildId)
              latest
